security:
  basic:
    enabled: false

spring:
  messages:
    basename: config/i18n/messages

  jpa:

    open-in-view: true
    hibernate:
      ddl-auto: create
      tool:
        hbm2ddl: DEBUG
    show-sql: true

logging:
    #file: /var/memento/security.log
    level:
        ROOT: INFO
        com.vaadin.data.util.LegacyPropertyHelper: DEBUG
        com.example: DEBUG